name: Street
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.50507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c9dbe5'
    - '#181913'
    - '#9e867a'
    - '#467394'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
